name: NestJS CI/CD Pipeline

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build-and-test:
    name: Build and Run Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.19'
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci

      - name: Run Linter
        run: npm run lint

      - name: Run Unit Tests
        run: npm run test

      - name: Build Project
        run: npm run build

  deploy:
    name: Deploy to Back4App
    needs: build-and-test
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Back4App CLI
        run: |
          VERSION="v0.1.2"
          FILENAME="b4a_${VERSION}_linux_amd64"
          URL="https://github.com/back4app/b4a-cli/releases/download/${VERSION}/${FILENAME}"

          echo "🔗 Downloading from: $URL"

          curl -L "$URL" -o b4a

          if [ ! -s b4a ]; then 
            echo "❌ Error: Download failed or file is empty!"; 
            exit 1; 
          fi

          chmod +x b4a
          echo "✅ CLI installed successfully!"

      - name: Configure and Deploy
        env:
          B4A_ACCOUNT_KEY: ${{ secrets.B4A_ACCOUNT_KEY }}
          B4A_APP_ID: ${{ secrets.B4A_APP_ID }}
        run: |
          ./b4a configure account --key $B4A_ACCOUNT_KEY
          ./b4a deploy --app $B4A_APP_ID
